export const ERROR_MESSAGES = {
  AUTH: {
    VALIDATION_FAILED: "Invalid authentication data",
    EMAIL_EXISTS: "Email already registered",
    USER_NOT_FOUND: "User not found",
    INVALID_PASSWORD: "Incorrect password",
    UNAUTHORIZED: "Unauthorized access",
    TOKEN_EXPIRED: "Session expired, please login again",
    TOKEN_INVALID: "Invalid authentication token",
    SIGNUP_FAILED: "Failed to register user",
    LOGIN_FAILED: "Failed to login user",
    LOGOUT_FAILED: "Failed to logout user",
  },
  RESUME: {
    NO_FILE_UPLOADED: "No resume file uploaded",
    INVALID_FILE_TYPE: "Only PDF, DOC, and DOCX resumes are allowed",
    UPLOAD_FAILED: "Failed to upload resume",
    DELETE_FAILED: "Failed to delete resume",
    REUPLOAD_FAILED: "Failed to replace resume",
    CLOUDINARY_CONFIG_MISSING: "Cloudinary configuration is missing",
    NOT_FOUND: "Resume not found",
    PARSE_FAILED: "Failed to parse resume",
    PARSE_ALREADY_IN_PROGRESS: "Resume parsing is already in progress",
    EMPTY_TEXT: "Could not extract text from the uploaded resume",
  },
};
